### ISSUE TITLE
开发者能不能在小黑屋应用内留下反馈方式，没找到怎么反馈

### ISSUE THREAD

**Issue by Edfgdz** [web1n/removeUser#1]
@web1n

**Comment by web1n** [comment]
酷安评论区

**Comment by Edfgdz** [comment]
不用酷安咋办

**Comment by web1n** [comment]
那你在哪里下载的？




-------- 原始邮件 --------
发件人：Edfgdz <notifications@github.com>
时间：周四 3月22日 14:26
收件人：web1n/removeUser <removeUser@noreply.github.com>
抄送：bin <wcxgzs@163.com>,State change <state_change@noreply.github.com>
主题：Re: [web1n/removeUser] 开发者能不能在小黑屋应用内留下反馈方式，没找到怎么反馈 (#1)

**Comment by Edfgdz** [comment]
酷安评论的话需要手机号，不想给.能不能用邮箱?

**Comment by web1n** [comment]
那请在这里反馈。

**Comment by Edfgdz** [comment]
​1增加按安装时间就近排序的功能
2夜间模式
3冻结应用后桌面图标可以不消失,无需去应用里面创建
4可以备份哪些应用被冻结,哪些应用没被冻结的功能,例如把备份文件导出后，下次安装小黑屋时，把备份文件导入后，上次被冻结的应用会被继续冻结掉,无需再一个个打开
5假如卸载小黑屋时没解冻应用，下次安装小黑屋后，希望各个应用能保持之前的状态,被冻的应用依然保持冻住的状态
@web1n

**Comment by web1n** [comment]
1.会加。
2.会加。
3.这不是小黑屋应该做的。
4.暂无意向。
5.小黑屋现在就是这样的。

**Comment by Edfgdz** [comment]
第三条不和软件冻结有关系吗？
第四条希望添加,如果因某些原因卸载重装后不至于重新来一遍

**Comment by web1n** [comment]
3.如果你了解冻结原理就不会这样子问了。
4.暂无意向不代表不加🙃。

**Comment by Edfgdz** [comment]
把软件解冻以后图标可不可以直接还显示在原来的桌面图标文件夹里面，不需要在重新添加回去,卸载之前进行解冻的话.

**Comment by web1n** [comment]
请联系桌面提供商，这不是的问题。


来自 魅蓝E2

-------- 原始邮件 --------
发件人：Edfgdz <notifications@github.com>
时间：周五 3月30日 14:56
收件人：web1n/removeUser <removeUser@noreply.github.com>
抄送：bin <wcxgzs@163.com>,Mention <mention@noreply.github.com>
主题：Re: [web1n/removeUser] 开发者能不能在小黑屋应用内留下反馈方式，没找到怎么反馈 (#1)
